config/routes.rb
Rails.application.routes.draw do
  root "accounts#show"

  resource :account, only: [:show]
  resources :deposits, only: [:new, :create]
  resources :transfers, only: [:new, :create]

  devise_for :users
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    transaction_manager = TransactionManager.new(current_user)

    @available = transaction_manager.available
    @transactions = transaction_manager.transactions
    @account_number = transaction_manager.account_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :authenticate_user!

  def create
    deposit_spec = DepositSpec.new(deposit_params)

    if deposit_spec.invalid?
      flash[:alert] = deposit_spec.errors.messages

      redirect_to new_deposit_path and return
    end

    transaction_manager = TransactionManager.new(current_user)

    transaction_manager.deposit(params[:amount])

    redirect_to root_path
  end

  private

  def deposit_params
    params.permit(:amount)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def create
    transfer_spec = TransferSpec.new(transfer_params)

    if transfer_spec.invalid?
      flash[:alert] = transfer_spec.errors.messages

      render :new, status: :bad_request and return
    end

    transaction_manager = TransactionManager.new(current_user)

    out = transaction_manager.transfer_to(transfer_spec.amount, transfer_spec.destination_account)

    if out == :ok
      flash[:notice] = "Transfer succeeded"
      redirect_to root_path

    elsif out == :insufficient_funds
      flash[:alert] = { amount:  "Not enough funds for transfer" }
      render :new, status: :bad_request and return

    elsif out == :same_account
      flash[:alert] = { amount:  "Must transfer to a different account" }
      render :new, status: :bad_request and return

    elsif out == :account_not_found
      flash[:alert] = { destination_account:  "No such account" }
      render :new, status: :bad_request and return

    elsif out == :invalid_amount
      flash[:alert] = { destination_account:  "Invalid transfer amount" }
      render :new, status: :bad_request and return
    end

  end

  private

  def transfer_params
    params.permit(:amount, :destination_account)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.erb
<% if user_signed_in? %>
  <h1 style="font-size: 24px;">Welcome <%= current_user.email %></h1>
<% end %>

<h2>Your account: <%= @account_number %></h2>

<h2>Transactions</h2>

<div>
  <table style="border-collapse: collapse; width: 100%;">
    <tr style="border-bottom: 1px solid #ccc;">
      <th style="padding: 8px;">Transaction Id</th>
      <th style="padding: 8px;">Transaction type</th>
      <th style="padding: 8px;">Amount</th>
    </tr>
    <% @transactions.each do |transaction| %>
      <tr>
        <td style="padding: 8px;"><%= transaction.id %></td>
        <td style="padding: 8px;"><%= transaction.transaction_type %></td>
        <td style="padding: 8px;"><%= transaction.amount %></td>
      </tr>
    <% end %>
  </table>
</div>

<div style="margin-top: 10px;">
  Total: <%= @available %>
  <%= link_to "Deposit funds", new_deposit_path, style: 'margin-left: 10px; color: #4CAF50; text-decoration: none; font-weight: bold;' %>
  <%= link_to "Transfer funds", new_transfer_path, style: 'margin-left: 10px; color: #4CAF50; text-decoration: none; font-weight: bold;' %>
</div>

<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, style: 'padding: 10px 20px; background-color: #ff4d4d; color: white; border: none; border-radius: 4px; cursor: pointer; margin-top: 10px;' %>
<% end %>

app/views/deposits/new.html.erb
<h1 style="font-size: 24px;">Add funds</h1>

<%= form_with(url: deposits_url, html: { style: 'display: flex; flex-direction: column;' }) do |form| %>
  <%= form.text_field :amount, style: 'padding: 5px; margin-bottom: 10px;' %>
  <%= form.submit "Deposit", style: 'padding: 10px 20px; background-color: #4CAF50; color: white; border: none; border-radius: 4px; cursor: pointer;' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transfer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= flash.to_hash %>
      </div>
    <% end %>

    <div style="width: 50%">
    <%= yield %>
    </div>

  </body>
</html>

app/views/transfers/new.html.erb
<%= form_with(url: transfers_url, html: { style: 'display: flex; flex-direction: column;' }) do |form| %>
  <div style="margin-bottom: 10px;">
    <%= form.label "Destination account", style: 'font-weight: bold;' %>
    <%= form.text_field :destination_account, style: 'padding: 5px;' %>
  </div>
  <div style="margin-bottom: 10px;">
    <%= form.label "Amount to transfer", style: 'font-weight: bold;' %>
    <%= form.text_field :amount, style: 'padding: 5px;' %>
  </div>
  <%= form.submit "Transfer", style: 'padding: 10px 15px; background-color: #4CAF50; color: white; border: none; border-radius: 4px; cursor: pointer;' %>
<% end %>